# 1)WAP using numpy to find degree of polynomial equation

In [4]:
import numpy as np 
   
pol = np.poly1d([7,2,4,1])  
print ("Degree of Polynomial: ", pol.order) 

list1=[2,2,4,5,6]
polyNew = np.poly1d(list1)
print ("Degree of Polynomial: ", (len(list1)-1))

Degree of Polynomial:  3
Degree of Polynomial:  4


# 2)WAP to find factorial of a number

In [5]:
a = int(input('Enter a number: '))
print(np.math.factorial(a))

Enter a number: 5
120


# 3)WAP to find roots of a Quadratic Equation

In [7]:
quad = [1, 2, 1]
print('Roots of equation: ',np.roots(quad))

Roots of equation:  [-1. -1.]


# 4)WAP to print diagonal elements of a matrix

In [8]:
import numpy as np 
         
matx = np.matrix('[6, 2, 1; 7, 4, 7; 1, 8, 3]')    
print('Diagonal Elements of Matrix: ',matx.diagonal())

Diagonal Elements of Matrix:  [[6 4 3]]


# 5)WAP to find profit or loss for a given CP and SP

In [26]:
import numpy as np
cp=np.array([[100,150,200,250]])
sp=np.array([[110,140,270,249]])

diff=list(np.subtract(sp,cp))
for x in diff:
    x

for i in range(len(x)):
    if x[i]<0:
        print('Loss of Rs',(-x[i]))
    else:
        print('Profit of Rs',x[i])
        

Profit of Rs 10
Loss of Rs 10
Profit of Rs 70
Loss of Rs 1


# 6)WAP to sort the matrix row wise and Column wise

In [36]:
mat = np.matrix('5, 4, 1; 7 ,4 ,9; 9, 2, 6')
mat.sort(axis=1)
print('Row wise sort')
print(mat)
print()

mat.sort(axis=0)
print('Column wise sort')
print(mat)

Row wise sort
[[1 4 5]
 [4 7 9]
 [2 6 9]]

Column wise sort
[[1 4 5]
 [2 6 9]
 [4 7 9]]
